add_newline = false
format = """\
    $username\
    $directory\
    $git_branch\
    $cmd_duration\
    $status\
    $character\
    """

[directory]
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch]($style) "

[cmd_duration]
format = "in [$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "

[character]
success_symbol = "[›](green)"
error_symbol = "[›](red)"
