- name: Configure packages
  include: pacman.yml
  become: yes

- name: Configure /ethereal
  include: ethereal.yml

- name: Place dotfiles
  include: dotfiles.yml
  tags: dotcopy

- name: Configure shell
  include: shell.yml

- name: Configure services
  include: services.yml
