- name: Create directory for zinit
  ansible.builtin.file:
    path: ~/.local/share/zinit
    state: directory

- name: Install zinit
  ansible.builtin.git:
    repo: "https://github.com/zdharma-continuum/zinit.git"
    dest: "~/.local/share/zinit/bin"
    update: false
    version: main
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Change shell
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: yes
