- name: Clone theme repo
  ansible.builtin.git:
    repo: "https://github.com/catppuccin/grub.git"
    dest: "/tmp/grub"
    update: false
    version: main
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Copy theme
  ansible.posix.synchronize:
    src: /tmp/grub/catppuccin-grub-theme
    dest: /usr/share/grub/themes/catppuccin-grub-theme
  delegate_to: "{{ inventory_hostname }}"

- name: Configure grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_THEME='
    line: GRUB_THEME="/usr/share/grub/themes/catppuccin-grub-theme/theme.txt"
  notify:
    - Recreate grub config
